### ISSUE TITLE
Import cJSON for deserialize TA response

### ISSUE THREAD

**Issue by howjmay** [DLTcollab/TA-endpoint#10]
We may need to deserialize the response from Tangle-Accelerator. Especially TA-endpoint needs to save the return UUID from Tangle-Accelerator.

So importing cJSON as JSON library is necessary.

**Comment by howjmay** [comment]
This issue will be implemented after [#507](https://github.com/DLTcollab/tangle-accelerator/issues/507) in tangle-accelerator has been implemented.

**Comment by splasky** [comment]
Move to tangle-accelerator [#571](https://github.com/DLTcollab/tangle-accelerator/issues/571)
