### ISSUE TITLE
Implement send value transaction

### ISSUE THREAD

**Issue by howjmay** [DLTcollab/TA-endpoint#11]
To support sending value transaction, we should port part of cclient onto TA-endpoint.
At least, we should make TA-endpoint be able to sign a transaction. The POW of the signed transaction can be done by TA by calling API `send_trytes`

Or if the user is a subscribing client, then the requests can attach with Alfred token. TA-endpoint can use this token to send value transactions

**Comment by splasky** [comment]
https://github.com/iotaledger/entangled/tree/develop/cclient

**Comment by splasky** [comment]
Move to tangle-acclerator [#572](https://github.com/DLTcollab/tangle-accelerator/issues/572)
