### ISSUE TITLE
Add data preprocessing function pointer 

### ISSUE THREAD

**Issue by howjmay** [DLTcollab/TA-endpoint#15]
The data transmitted to TA-endpoint sometimes needs to be done with some certain preprocess which may depends on the scenario. 
I.E. a battery sends raw power consumption data to TA-endpoint. TA-endpoint would process the data including appending data receiving time, client ID, hardware ID, etc. Then the proccessed can be encrypted, encoded and transmit to tangle.

We need a function to handle this task, and in order to meet different situation using a function pointer may be better.

**Comment by splasky** [comment]
Move to tangle-accelerator [#574](https://github.com/DLTcollab/tangle-accelerator/issues/574)
