### ISSUE TITLE
Error when response

### ISSUE THREAD

**Issue by splasky** [DLTcollab/TA-endpoint#21]
After remove openssl submodule, the response from ta-accerlator appear.
The log is here:
```
HTTP Response: <html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.14.0 (Ubuntu)</center>
</body>
</html>
```

**Comment by jserv** [comment]
Improve the descriptions about this issue!
Read this guideline carefully: https://github.com/necolas/issue-guidelines/blob/master/CONTRIBUTING.md

**Comment by howjmay** [comment]
close this, since it has been solved
