### ISSUE TITLE
Synchronize with latest Mbed TLS

### ISSUE THREAD

**Issue by splasky** [DLTcollab/TA-endpoint#27]
The new version of mbedtls has been released yestarday. The new version is 2.16.5 Our version is 2.16.2 should we update it?

Release message:
https://github.com/ARMmbed/mbedtls/releases/tag/mbedtls-2.16.5

**Comment by howjmay** [comment]
Currently we haven't hooked up to a certain tag or commit on `mbedtls`. We may need to think about this now.
