### ISSUE TITLE
Implemnet CLI for setting configures

### ISSUE THREAD

**Issue by splasky** [DLTcollab/TA-endpoint#29]
How about using cli at the first step? 
I think it may be easier to implement

_Originally posted by @HowJMay in https://github.com/DLTcollab/TA-endpoint/pull/26_

**Comment by howjmay** [comment]
The original description is here 
https://github.com/DLTcollab/TA-endpoint/pull/26#discussion_r384253125

**Comment by howjmay** [comment]
We need to implement CLI interface for the following parameters.
* host
* port

**Comment by splasky** [comment]
CLI interface has already been implemented inside endpoint.c. Did you mean implement inside main.c ?

**Comment by howjmay** [comment]
@splasky  `host` and `port` should be able to set by CLI.

**Comment by splasky** [comment]
Move to tangle-accelerator [#577](https://github.com/DLTcollab/tangle-accelerator/issues/577)
