### ISSUE TITLE
Encapsulated uart implement into HAL

### ISSUE THREAD

**Issue by splasky** [DLTcollab/TA-endpoint#32]
These operations should be encapsulated in HAL.

_Originally posted by @jserv in https://github.com/DLTcollab/TA-endpoint/pull/30_

**Comment by howjmay** [comment]
@splasky Maybe we could implement the following methods
* device_t* hal_init(device_t* dv)
* void hal_finit(device_t* dv)
* retcode_t hal_get_id(device_t* dv)
* retcode_t hal_get_key(device_t* dv)

**======IO read/write======**
* retcode_t hal_write(device_t* dv, enum interface)
* retcode_t hal_read(device_t* dv, enum interface)

**Comment by howjmay** [comment]
The original request of this issue is at https://github.com/DLTcollab/TA-endpoint/pull/30#discussion_r388163689

**Comment by jserv** [comment]
> Maybe we could implement the following methods
> * device_t* hal_init(device_t* dv)
> * void hal_finit(device_t* dv)
> * retcode_t hal_get_id(device_t* dv)
> * retcode_t hal_get_key(device_t* dv)
> 
> **======IO read/write======**
> 
> * retcode_t hal_write(device_t* dv, enum interface)
> * retcode_t hal_read(device_t* dv, enum interface)

Use `hal::get_id` or `hal::write` while talking about HAL design.

**Comment by splasky** [comment]
The UART operators interface has already implemented inside hal, so I close this issue.
