### ISSUE TITLE
Cleanup code base

### ISSUE THREAD

**Issue by splasky** [DLTcollab/TA-endpoint#33]
Create a new issue for cleaning up existing codebase.

_Originally posted by @jserv in https://github.com/DLTcollab/TA-endpoint/pull/26_

Need to cleanup code base with some necessary reason:
1. debug, hal, compiler flags, cross compile flag are mixed together, should cleanup and simplify.
2. After cleanup can make unittest and CI/CD easily.

**Comment by howjmay** [comment]
The original request is at https://github.com/DLTcollab/TA-endpoint/pull/26#discussion_r386259430

**Comment by howjmay** [comment]
This is duplicate to #31
