### ISSUE TITLE
Rewrite formatter

### ISSUE THREAD

**Issue by howjmay** [DLTcollab/TA-endpoint#4]
The current formatter has enormous bug. We need to implement a new one

**Comment by splasky** [comment]
Use llvm coding standard instead?

**Comment by jserv** [comment]
Did you mean `clang-format`?

**Comment by splasky** [comment]
Yes, we can put it into the hook folder.

**Comment by jserv** [comment]
We shall stick on consistent style setting as dcurl and tangle-acclerator does. Read clang-format manual to exclude the unexpected code snip.

**Comment by howjmay** [comment]
We can use the same `.clang-format` file in TA. However the file `/hooks/formatter` should be rewrite, since it can't format all the files under TA-enpoint
