### ISSUE TITLE
Use logger in debug level instead of macro condition `ifdef`

### ISSUE THREAD

**Issue by howjmay** [DLTcollab/TA-endpoint#56]
For example at [here](https://github.com/DLTcollab/TA-endpoint/pull/40/files#diff-04fda79ef2551da671c8e121e061d28bR34), we use `ifdef` to decide whether to print debugging message. However, once we finish implementing logger, then we should use logger instead of `ifdef` and `printf()`

**Comment by splasky** [comment]
Move to tangle-accelerator [#578](https://github.com/DLTcollab/tangle-accelerator/issues/578)
