### ISSUE TITLE
Formalize unittests in TA-endpoint

### ISSUE THREAD

**Issue by howjmay** [DLTcollab/TA-endpoint#7]
The current implementation of tests are in a really rough version. We should use introduce some testing framework for our tests.

We needs to implement CI process and sanitizers for different CI scenarios.

**Comment by howjmay** [comment]
Currently we use unittest framework [unity](https://www.throwtheswitch.org/unity)

**Comment by marktwtn** [comment]
I have rewritten the tests with **Unity** testing framework.

However, the **Unity** testing framework can not be installed easily.
(Check https://github.com/ThrowTheSwitch/Unity/issues/302 for more reference.)

Other projects like [iota_common](https://github.com/iotaledger/iota_common) solve the problem with **Bazel**.

I need to figure out how to use **Unity** correctly.

**Comment by howjmay** [comment]
Or is there any other simple pure C test framework.

**Comment by marktwtn** [comment]
> Or is there any other simple pure C test framework.

Well, all we have to do is to download the specific version of **Unity** and assign the correct path for the header and the source code.
It would not be hard.

If making the **Unity** as a git submodule is acceptable, I will move on for the modification.
Or we could just download it and remove it when we do the project cleaning.
